---
version: '2'
services:

  elasticsearch:
    image: elasticsearch:latest
    network_mode: host
    extra_hosts:
      - "moby:127.0.0.1"

  kibana:
    image: kibana:latest
    network_mode: host
    environment:
      ELASTICSEARCH_URL: "http://localhost:9200"
